### ISSUE TITLE
Error with VPN

### ISSUE THREAD

**Issue by paradocx** [itewqq/MathF#4]
If I don't use VPN tool, it shows 'NULL'.  While I use VPN and locate at U.S., it shows token error. How can I trackle this problem?

**Comment by itewqq** [comment]
@paradocx Well, I added some anti-abuse strategies recently. The "Token error" usually happens when you failed the robot test. Are you programmatically sending requests?

In my enviroment, it's working correctly whether I'm using a VPN or not.

![image](https://user-images.githubusercontent.com/30570177/107599502-b33ee780-6c5b-11eb-96f5-1b5e4e8ec043.png)

**Comment by itewqq** [comment]
This issue is closed because it has not been answered for a long time. Feel free to reopen it if you have questions.
